server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  api-gateway:
    default-name: Default name is API-GATEWAY

## Manually configure routes
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: department-service
#              uri: lb://DEPARTMENT-SERVICE
#              predicates:
#                - Path=/api/departments/**
#            - id: employee-service
#              uri: lb://EMPLOYEE-SERVICE
#              predicates:
#                - Path=/api/employees/**

## Auto-discover routes using service discovery
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
