server:
  port: 8081

spring:
  application:
    name: EMPLOYEE-SERVICE

  employee:
    default-name: Default name is EMPLOYEE-SERVICE

  datasource:
    url: jdbc:h2:mem:employeedb
    driver-class-name: org.h2.Driver
    username: virak
    password: root

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
